### ISSUE TITLE
Can't  Load the project in Visual Studio 2015

### ISSUE THREAD

**Issue by CharguiTaieb** [BaristaLabs/chrome-dev-tools-generator#2]
![888888888888888](https://user-images.githubusercontent.com/4105665/28749482-aef7162a-74c0-11e7-82eb-3ae4d05c839c.png)

**Comment by pebezo** [comment]
It worked with VS 2017

**Comment by Oceanswave** [comment]
Will need to find my VM that has VS2015 to ensure this fully, but I believe your issue is related to .Net Core support -- ensure you have the [.Net Core Tools for VS2015 installed](https://aka.ms/dotnet-standard-support-vs2015-2.0.0-win-x86).

**Comment by Oceanswave** [comment]
So, bad news I fired up my old VS2015 VM and encountered this same issue.

Upon researching this, unfortunately Microsoft has decided not to pursue support for the new csproj file in Visual Studio 2015. So Visual Studio 2017 support is required. Installing the above tools will do nothing.

See the following issue for the details:
https://github.com/dotnet/cli/issues/5725

You can still build and run the solution at the command line, or use tools like Rider or VSCode + C#, but VS2015 is not supported.
