### ISSUE TITLE
Ws_Error throw e.Exception and how to catch it

### ISSUE THREAD

**Issue by ToCSharp** [BaristaLabs/chrome-dev-tools-generator#5]
Ws_Error throw e.Exception and how to catch it in App

        #region EventHandlers
        private void Ws_Error(object sender, SuperSocket.ClientEngine.ErrorEventArgs e)
        {
            LogError("Error: {exception}", e.Exception);
            throw e.Exception;
        }

**Comment by Oceanswave** [comment]
Do you have repro steps to throw the error?

**Comment by ToCSharp** [comment]
If we close chrome window while WebSocket working, we will get Ws_Error. It crashes app

**Comment by Oceanswave** [comment]
I've added a unit test demonstrating this here:

https://github.com/BaristaLabs/chrome-dev-tools-runtime/blob/master/BaristaLabs.ChromeDevTools.Runtime.Tests/Tests/ErrorHandlingUnitTests.cs

Feel free to reopen if you don't feel this represents the problem
