### ISSUE TITLE
NuGet

### ISSUE THREAD

**Issue by pebezo** [BaristaLabs/chrome-dev-tools-generator#6]
Do you have plans to put this library on NuGet? Thanks.

**Comment by ToCSharp** [comment]
This is generator. Better not this project, but [chrome-dev-tools-sample](https://github.com/BaristaLabs/chrome-dev-tools-sample), please. 
And maybe change names: chrome-dev-tools => chrome-dev-tools-generator, chrome-dev-tools-sample => chrome-dev-tools. ChromeDevTools is used in [MasterDevs/ChromeDevTools ](https://github.com/MasterDevs/ChromeDevTools). It would be great. Your project is more usefull for me.

**Comment by pebezo** [comment]
Yes, I was thinking about the sample / generated project. I also agree on the name, but that's a decision for @Oceanswave 

I looked at  MasterDevs/ChromeDevTools as well, but I needed version 1.2 so I went with this one.

**Comment by Oceanswave** [comment]
Great ideas! The name change will clear up some confusion too I think.

I kinda wanted folks to be able to generate their own wrapper, but if the easier path is to have a nuget library, I'm totally with that.

Let me find some time and knock some of these out.

**Comment by ToCSharp** [comment]
I use chrome-dev-tools-sample in [AsyncChromeDriver](https://github.com/ToCSharp/AsyncChromeDriver) and have [NuGet](https://www.nuget.org/packages/AsyncChromeDriver). You can get all functionality. Thanks to @Oceanswave
 But it is for .NET Framework. I think, I'll wait for .NETStandard 2.0.

**Comment by Oceanswave** [comment]
So thanks to your ideas @ToCSharp I've renamed this project to chrome-dev-tools-generator and the sample project to chrome-dev-tools-runtime, will work on putting that project on github.

**Comment by Oceanswave** [comment]
I've published the runtime library to nuget at the location below. It should show up after the package is indexed.

https://www.nuget.org/packages/BaristaLabs.ChromeDevTools.Runtime/

Thanks all!
